# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/class18/gaoruiyuan/conv2d/conv2d.srcs/sources_1/ip/image_input/image_input.xci
# IP: The module: 'image_input' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/class18/gaoruiyuan/conv2d/conv2d.srcs/sources_1/ip/image_input/image_input_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_input'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/class18/gaoruiyuan/conv2d/conv2d.srcs/sources_1/ip/image_input/image_input.xci
# IP: The module: 'image_input' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/class18/gaoruiyuan/conv2d/conv2d.srcs/sources_1/ip/image_input/image_input_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_input'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
